config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
resources :groups do
  resources :entitys
end
  # Defines the root path route ("/")  
  root "splashs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :user
  belongs_to :group
  validates :name, presence: true
  validates :amount, presence: true, numericality: { only_integer: true, greater_than: 0 }
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :entities, dependent: :destroy

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: %i[admin editor], multiple: false) ##
  ############################################################################################

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :groups, dependent: :destroy
  has_many :entities, dependent: :destroy
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/entitys_controller.rb
class EntitysController < ApplicationController
  access user: :all, admin: :all
  def index
    @group = Group.find(params[:group_id])
    @entitys = Entity.where(group_id: @group.id, user_id: current_user.id)
  end

  def new
    @entity = Entity.new
  end

  def create
    @entity = Entity.new(entity_params)
    @entity.user_id = current_user.id
    if @entity.save
      redirect_to group_entitys_path(@entity.group_id)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def entity_params
    params.require(:entity).permit(:name, :amount, :user_id, :group_id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  access user: :all, admin: :all

  def index
    @groups = current_user.groups
    @count = @groups.count
  end

  def show
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user_id = current_user.id
    if @group.save
      redirect_to groups_path
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def group_params
    params.require(:group).permit(:name, :icon, :user_id)
  end
end

app/controllers/splashs_controller.rb
class SplashsController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entitys_helper.rb
module EntitysHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/entitys/_form.html.erb
<%= form_with model: @entity, url:group_entitys_path do |form| %>
  <% if @entity.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@entity.errors.count, "error") %> prohibited this entity from being saved:</h2>
        <% @entity.errors.each do |error| %>
          <h5 class="text-center text-secondary"><%= error.full_message %></h5>
        <% end %>
    </div>
  <% end %>

  <div class="p-2">
    <%= form.text_field :name, class: 'form-control', placeholder: 'Name', required: true %>
  </div>

  <div class="p-2">
    <%= form.number_field :amount, class: 'form-control', placeholder: 'Amount ', required: true  %>
  </div>

  <div class="select-field">
    <%= form.label :group_id, 'Category',class:"pe-1 fw-semibold fs-4 text-secondary" %>
    <%= form.collection_select :group_id, current_user.groups, :id, :name ,class:"p-1 fw-semibold" %>
  </div>

  <div class="text-light footer d-flex justify-content-center p-3">
    <%= form.submit 'Create transaction', class: 'button btn p-2' %>
  </div>
<% end %>

app/views/entitys/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="w-50 m-auto">
  <h1 class="text-center">Entities</h1>
  <ul class="container  list-unstyled">
  <%=render 'groups/group', group:@group%>
  </ul>

<% if @entitys.empty? %>
  <h4 class="text-center text-secondary">There are not transactions yet!</h4>
  <p class="text-center text-secondary">Create a transaction for this category by clicking on the button below.</p>
<% else %>
  <ul class="container custom-container">
    <% @entitys.each do |entity| %>
      <li class="d-flex justify-content-between border bg-light p-1 mt-3 list-unstyled">
        <div class="px-2 d-flex flex-column">
          <h5><%= entity.name %></h5>
          <p class="fs-6"><%= @group.created_at.strftime("%d %h %Y")%> at <%= @group.created_at.strftime("%l.%M%P")%></p>
        </div>
        <div class="px-2 fw-semibold fs-6 text-secondary ">
          <span class="">$<%= entity.amount %></span>
        </div>
      </li>
    <% end %>
  </ul>
<% end %>
<div class="text-light footer d-flex justify-content-center container p-2">
  <%= button_to 'New Transaction', new_group_entity_path(group_id: @group.id), method: :get, class: 'btn button p-2' %>
</div>
</div>

app/views/entitys/new.html.erb
<div class="container">
<h1 class="text-center pt-3">TRANSACTIONS</h1>
<%= render "form", entity: @entity %>
</div>

app/views/groups/_form.html.erb
<div class="container">
 <%= form_with(model: group) do |form| %>
    <% if @group.errors.any? %>
        <% @group.errors.full_messages.each do |message|%>
            <h5 class="text-center text-secondary"><%= message %> </h5>
        <%end%>
    <%end%>
    <div class="p-2">
     <%= form.text_field :name , class: 'form-control', placeholder:"Name" %>
    </div>
    <div class="p-2">
     <%= form.text_field :icon , class: 'form-control', placeholder:"Icon link"%>
    </div>
    <div class="text-light footer d-flex justify-content-center p-3">
     <%= form.submit "Create Group", class: 'button btn' %>
    </div>

 <% end %>
</div>

app/views/groups/_group.html.erb
<li class="groups-list-item">
    <div class="d-flex justify-content-between border mb-1 p-2 mt-3">
        <div class="d-flex justify-content-start">
            <div class="">
              <img src="<%= group.icon %>" alt="Category icon image" class="rounded">
            </div>
            <div class="text-center">
              <h2><%= group.name %></h2>
              <p><%= group.created_at.strftime("%d %h %Y") %></p>
            </div>
        </div>
        <div class="px-2 d-flex justify-content-between fw-semibold fs-6 text-secondary ">
            <% total = 0.00 %>
            <% group.entities.each {|entity| total += entity.amount} %>
            <span class="amount">Total Amount: $</span>
            <span><%= total %></span>
        </div>
    </div>
</li>

app/views/groups/index.html.erb
<%=render 'shared/groupindex',groups:@groups%>

app/views/groups/new.html.erb
<h4 class="text-center mt-4">Create new group</h4>
<%= render "form", group: @group %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% if user_signed_in? %>
    <%= render 'shared/navbar' %>
  <% end %>
  <%= yield %>
    <% if user_signed_in? %>
      <%=render 'shared/footer'%>
  <% end %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="bg-secondary position-absolute bottom-0 w-100">
  <div class="text-center d-flex justify-content-between p-2">
    <p class="mb-0">Designed by <strong>Muskan Gupta</strong></p>
    <p class="mb-0">Copyright &copy; 2023</p>
  </div>
</footer>

app/views/shared/_groupindex.html.erb
<h2 class="text-center mt-4  text-muted">CATEGORIES</h2>
<div class="container custom-width">
    <% if groups.empty? %>
      <h4 class="text-center text-secondary">There are not categories yet!</h4>
      <p class="text-center text-secondary">Create your first category by clicking on the button below.</p>
    <% else %>
      <ul class=" list-unstyled">
        <% groups.each do |group| %>
         <%= link_to group_entitys_path(group.id), class: 'text-decoration-none' do %>
         <%=render 'groups/group', group:group %>
         <%end%>
        <% end %>
      </ul>
    <% end %>

  <div class="p-3">
    <%= link_to 'New Category', new_group_path, method: :get, class: 'button btn border  p-2 fs-5 w-100' %>
  </div>
</div> 

app/views/shared/_login.html.erb
<p style="color: green"><%= notice %></p>
<% if user_signed_in? %>
    <%= button_to "Log out", destroy_user_session_path, class: "button btn text-light" ,method: :delete %>
<% else %>
    <%= link_to "Log in", new_user_session_path , class: "button btn text-light"%>
    <%= link_to "Sign up", new_user_registration_path , class: "button btn text-light"%>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg background">
  <div class="container">
        <%=link_to 'Bk' ,:back, class: "text-decoration-none fs-2 text-dark" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav align-items-center mb-2 mb-lg-0">
        <li class="nav-item me-4">
          <%=link_to 'Category' , groups_path, class: "text-decoration-none text-dark fs-5"%>
        </li>
        <li class="nav-item ms-4">
          <%=render 'shared/login'%>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/splashs/index.html.erb
<% if user_signed_in? %>
       <div class="container d-flex flex-column ">
         <p class="text-center">Welcome, <%= current_user.name %></p>
        <p class="text-center">You are signed in!</p>
        <%= link_to 'Go to categories', groups_path,  method: :get,  class: 'btn btn-primary  w-75 mt-5 ms-5' %>
        <%= button_to "Log out", destroy_user_session_path, class: "btn btn-primary  w-75 mt-2 ms-5" ,method: :delete %>
       </div>
<% else %>
    <div class="container-fluid text-center">
     <div class="position-absolute top-50 start-50 translate-middle w-50">
       <h1 >Bk Library</h1>
       <div class="d-flex flex-column ms-5">
           <%= link_to  'Log in', user_session_path, class: 'btn btn-primary w-75 mt-5' %>
           <%= link_to  'Sign Up', new_user_registration_path, method: :get, class: 'btn btn-success w-75 mt-3' %>
       </div>
     </div>
    </div>
<%end%>